Add safeguard to gc

diff --git a/bin/gc b/bin/gc
--- a/bin/gc
+++ b/bin/gc
@@ -3,6 +3,12 @@
 # Git Clean
 # When what you've been drafting is not worth a commit.
 
+# Ensure we're in a git repository
+if ! git rev-parse --is-inside-work-tree &> /dev/null; then
+	echo "Error: gc must be run in a Git repository."
+	exit 1
+fi
+
 git add --all
 git stash
 git stash drop stash@{0}
