More safety checks

diff --git a/scripts/gd b/scripts/gd
--- a/scripts/gd
+++ b/scripts/gd
@@ -6,8 +6,8 @@ set -eu
 
 # Ensure we're in a git repository.
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-	echo "Error: gd must be run in a Git repository."
-	exit 1
+    echo "Error: gd must be run in a Git repository."
+    exit 1
 fi
 
 git add --all
diff --git a/scripts/gl b/scripts/gl
--- a/scripts/gl
+++ b/scripts/gl
@@ -6,11 +6,11 @@ set -eu
 
 # Determine default branch
 if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-	default_branch=$(git rev-parse --abbrev-ref origin/HEAD)
-	default_branch=$(echo "$default_branch" | sed 's|^origin/||')
+    default_branch=$(git rev-parse --abbrev-ref origin/HEAD)
+    default_branch=$(echo "$default_branch" | sed 's|^origin/||')
 else
-	echo "Error: gl must be run in a Git repository."
-	exit 1
+    echo "Error: gl must be run in a Git repository."
+    exit 1
 fi
 
 # Determine current branch
@@ -20,16 +20,16 @@ git_cmd="git log --oneline" # base git log command
 
 # Reverse print order if on a branch other than the default one.
 match_ui() {
-	if [ "$branch" != "$default_branch" ]; then
-		git_cmd="$git_cmd --reverse"
-	fi
+    if [ "$branch" != "$default_branch" ]; then
+        git_cmd="$git_cmd --reverse"
+    fi
 }
 
 # Execute the git command and exit with its status.
 execute() {
-	match_ui # always match UI order.
-	eval "$git_cmd"
-	exit $?
+    match_ui # always match UI order.
+    eval "$git_cmd"
+    exit $?
 }
 
 # Set n to empty string if $1 is unbound.
@@ -37,24 +37,24 @@ n="${1:-}"
 
 # Show N commits if provided as a parameter. Should take precedence over everything else.
 if [ -n "$n" ]; then
-	git_cmd="$git_cmd -$n"
-	execute
+    git_cmd="$git_cmd -$n"
+    execute
 fi
 
 # Limit number of printed commits to prevent scrolling in terminal.
 no_scroll() {
-	terminal_height=$(($(tput lines) - 2)) # Deduct 2 (1 for cmd, 1 for prompt).
-	line_count=$(eval "$git_cmd | wc -l") # Count how many commits would be printed.
+    terminal_height=$(($(tput lines) - 2)) # Deduct 2 (1 for cmd, 1 for prompt).
+    line_count=$(eval "$git_cmd | wc -l") # Count how many commits would be printed.
 
-	if [ "$line_count" -gt "$terminal_height" ]; then
-		git_cmd="$git_cmd -$terminal_height"
-	fi
+    if [ "$line_count" -gt "$terminal_height" ]; then
+        git_cmd="$git_cmd -$terminal_height"
+    fi
 }
 
 # Show all commits on default branch.
 if [ "$branch" = "$default_branch" ]; then
-	no_scroll # Or however many fit in the terminal.
-	execute
+    no_scroll # Or however many fit in the terminal.
+    execute
 fi
 
 # Compare to default branch on other branches.
diff --git a/scripts/gpr b/scripts/gpr
--- a/scripts/gpr
+++ b/scripts/gpr
@@ -6,32 +6,32 @@ set -eu
 
 # Determine default branch.
 if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-	default_branch=$(git rev-parse --abbrev-ref origin/HEAD)
-	default_branch=${default_branch#"origin/"}
+    default_branch=$(git rev-parse --abbrev-ref origin/HEAD)
+    default_branch=${default_branch#"origin/"}
 else
-	echo "Error: gpr must be run in a Git repository."
-	exit 1
+    echo "Error: gpr must be run in a Git repository."
+    exit 1
 fi
 
 # Get origin URL and ensure it's in GitHub.
 origin=$(git remote get-url origin)
 case "$origin" in
-	*github.com*)
-		;;
-	*)
-		echo "Error: gpr requires origin url in GitHub."
-		exit 1
-		;;
+    *github.com*)
+        ;;
+    *)
+        echo "Error: gpr requires origin url in GitHub."
+        exit 1
+        ;;
 esac
 
 # Extract the repository URL in a format that can be opened in a browser.
 if echo "$origin" | grep -q 'git@github.com:'; then
-	repo_url="https://github.com/$(echo "$origin" | sed 's/^.*github.com://;s/.git$//')"
+    repo_url="https://github.com/$(echo "$origin" | sed 's/^.*github.com://;s/.git$//')"
 elif echo "$origin" | grep -q 'https://github.com/'; then
-	repo_url=$(echo "$origin" | sed 's/.git$//')
+    repo_url=$(echo "$origin" | sed 's/.git$//')
 else
-	echo "Error: gpr only supports ssh and https-cloned repos."
-	exit 1
+    echo "Error: gpr only supports ssh and https-cloned repos."
+    exit 1
 fi
 
 # Get current branch name.
@@ -39,8 +39,8 @@ branch=$(git rev-parse --abbrev-ref HEAD)
 
 # Open the repo on default branch.
 if [ "$branch" = "$default_branch" ]; then
-	open "$repo_url"
-	exit $?
+    open "$repo_url"
+    exit $?
 fi
 
 owner=$(echo "$repo_url" | cut -d'/' -f4)
@@ -49,9 +49,9 @@ repo=$(echo "$repo_url" | cut -d'/' -f5)
 pr_url=$(gh api "repos/$owner/$repo/pulls?head=$owner:$branch" --jq '.[0].html_url')
 
 if [ -z "$pr_url" ]; then
-	# TODO: push branch if it hasn't been pushed to remote.
-	open "$repo_url/pull/$branch"
-	exit 0
+    # TODO: push branch if it hasn't been pushed to remote.
+    open "$repo_url/pull/$branch"
+    exit 0
 fi
 
 # Get urls of open Safari tabs via AppleScript.
@@ -72,10 +72,10 @@ EOA
 IFS=', ' # Convert the output to a list
 
 for url in $urls; do
-	if echo "$url" | grep -q "$pr_url"; then
-		open "$url"
-		exit 0
-	fi
+    if echo "$url" | grep -q "$pr_url"; then
+        open "$url"
+        exit 0
+    fi
 done
 
 # Otherwise fall back to old behavior.
